fix: added grafana-umh to auto build

diff --git a/deployment/grafana-umh/Dockerfile b/deployment/grafana-umh/Dockerfile
--- a/deployment/grafana-umh/Dockerfile
+++ b/deployment/grafana-umh/Dockerfile
@@ -49,6 +49,10 @@ RUN if [ ! -z "${GF_INSTALL_PLUGINS}" ]; then \
           pluginUrl=$(echo "$plugin" | cut -d';' -f 1); \
           pluginInstallFolder=$(echo "$plugin" | cut -d';' -f 2); \
           grafana-cli --pluginUrl ${pluginUrl} --pluginsDir "${GF_PATHS_PLUGINS}" plugins install "${pluginInstallFolder}"; \
+          # Fail build if this has failed ! \
+            if [ $? -ne 0 ]; then \
+                exit 1; \
+            fi \
         else \
           grafana-cli --pluginsDir "${GF_PATHS_PLUGINS}" plugins install ${plugin}; \
         fi \
