feat:goodnight

diff --git a/.github/workflows/test-kafka-to-postgresql-v2.yaml b/.github/workflows/test-kafka-to-postgresql-v2.yaml
--- a/.github/workflows/test-kafka-to-postgresql-v2.yaml
+++ b/.github/workflows/test-kafka-to-postgresql-v2.yaml
@@ -12,12 +12,22 @@ jobs:
     steps:
       - uses: actions/checkout@v3
 
+      # Teardown, allowing for repeated local testing
+      - name: Teardown old tests
+        run: |
+          docker stop redpanda-1 || true
+          docker stop timescaledb-1 || true
+          docker stop kafka-to-postgresql-v2-1 || true          
+          docker container prune -f || true
+          docker volume prune -f || true
+          docker system prune -f || true
+
       - name: Create Docker Network
         run: docker network create my_network
 
       - name: Start TimescaleDB
         run: |
-          docker run -d --name timescaledb-1 \
+          docker run -d --name timescaledb-1 --network=my_network \
           -e POSTGRES_PASSWORD=yourpassword \
           -p 5432:5432 \
           timescale/timescaledb:latest-pg15
@@ -55,7 +65,7 @@ jobs:
               timestamp TIMESTAMPTZ NOT NULL,
               name TEXT NOT NULL,
               origin TEXT NOT NULL,
-              asset SERIAL REFERENCES assets(id) NOT NULL
+              asset SERIAL REFERENCES assets(id) NOT NULL,
               value REAL
             );
 
@@ -63,7 +73,7 @@ jobs:
               timestamp TIMESTAMPTZ NOT NULL,
               name TEXT NOT NULL,
               origin TEXT NOT NULL,
-              asset SERIAL REFERENCES assets(id) NOT NULL
+              asset SERIAL REFERENCES assets(id) NOT NULL,
               value TEXT
             );
 
@@ -92,15 +102,33 @@ jobs:
           --memory 1G \
           --reserve-memory 0M \
           --node-id 0 \
-          --check=false
+          --check=false \
+          --kafka-addr=0.0.0.0:9092 \
+          --advertise-kafka-addr=redpanda-1:9092
+
+      # Validate redpanda is reachable
+      - name: Check Redpanda REST Interface
+        run: |
+          success=false
+          for i in {1..5}; do
+              echo "Attempt $i to check Redpanda REST interface..."
+              if curl -f http://localhost:8082/topics; then
+                  echo "Successfully connected to Redpanda REST interface!"
+                  success=true
+                  break
+              else
+                  echo "Failed to connect, retrying in 1 second..."
+                  sleep 1
+              fi
+          done
+          if [ "$success" = false ]; then
+              echo "Failed to connect to Redpanda REST interface after 5 attempts."
+              exit 1
+          fi
 
       # Build the Docker image
       - name: Build Docker Image
         run: docker build -t kafka-to-postgresql-v2:latest -f ./deployment/kafka-to-postgresql-v2/Dockerfile .
-
-      # Wait for 5 seconds (give redpanda some time)
-      - name: Wait for 5 seconds
-        run: sleep 5
 
       # Run the Docker image
       - name: Run Docker Image
@@ -114,60 +142,49 @@ jobs:
           -e POSTGRES_SSL_MODE=disable \
           -e KAFKA_BROKERS=redpanda-1:9092 \
           -e KAFKA_HTTP_BROKERS=redpanda-1:8082 \
+          -e LOGGING_LEVEL=DEVELOPMENT \
           kafka-to-postgresql-v2:latest
 
-      # Install Redpanda tool (rpk)
-      - name: Install Redpanda Tool
-        run: |
-          cd /tmp
-          curl -fL https://github.com/redpanda-data/redpanda/releases/latest/download/rpk-linux-amd64.zip -o rpk.zip
-          unzip -o rpk.zip
-          chmod +x rpk
-          sudo mv rpk /usr/bin
-
-      # Get ip of kafka
       - name: Get Redpanda IP Address
         id: redpanda_ip
         run: |
           IP=$(docker inspect -f '{{range.NetworkSettings.Networks}}{{.IPAddress}}{{end}}' redpanda-1)
           echo "REDPANDA_IP=$IP" >> $GITHUB_ENV
 
+      - name: Install kafkacat
+        run: |
+          sudo apt-get update -y
+          sudo apt-get install -y kafkacat
       # Send message to Kafka
       - name: Use Redpanda IP with rpk
         run: |
-          echo "Redpanda IP: ${{ env.REDPANDA_IP }}"
-          /usr/bin/rpk topic create umh.v1.test._historian --brokers ${{ env.REDPANDA_IP }}:9092
-          (echo '{"timestamp_ms": 1, "hello":"world"}' & sleep 2; kill -INT $!) | /usr/bin/rpk topic produce umh.v1.test._historian --brokers ${{ env.REDPANDA_IP }}:9092 &
+          docker exec redpanda-1 rpk topic create umh.v1.test._historian --brokers localhost:9092
+          
+          docker run --network=my_network edenhill/kcat:1.7.1 -b redpanda-1 -L
+          docker run --network=my_network edenhill/kcat:1.7.1 -b redpanda-1 -P -v -t umh.v1.test._historian
+          
+          echo '{"timestamp_ms": 1, "hello":"world"}' > /tmp/message.json
+          docker run --network=my_network --mount type=bind,source=/tmp/message.json,target=/message.json edenhill/kcat:1.7.1 -P -b redpanda-1:9092 -t umh.v1.test._historian /message.json
+          
 
-      # Wait for 10 seconds
-      - name: Wait for 10 seconds
-        run: sleep 10
+      # Wait for 20 seconds
+      - name: Wait for 20 seconds
+        run: sleep 20
 
       # Check for entries in the tag table
       - name: Check Database
         env:
           PGPASSWORD: yourpassword
         run: |
-          docker exec timescaledb-1 psql -U youruser -d yourdb -c "SELECT * FROM tag;"
-          docker exec timescaledb-1 psql -U youruser -d yourdb -c "SELECT * FROM tag_string;"
-          docker exec timescaledb-1 psql -U youruser -d yourdb -c "SELECT * FROM asset;"
+          docker exec timescaledb-1 psql -U postgres -d yourdb -c "SELECT * FROM tag;"
+          docker exec timescaledb-1 psql -U postgres -d yourdb -c "SELECT * FROM tag_string;"
+          docker exec timescaledb-1 psql -U postgres -d yourdb -c "SELECT * FROM assets;"
 
-      # Teardown, allowing for repeated local testing
-      - name: Teardown
+      # Log
+      - name: Log
         if: always()
         run: |
-          echo "Logging and stopping redpanda"
-          #docker logs redpanda-1
-          docker stop redpanda-1 || true
-                    
-          echo "Logging and stopping postgres"          
-          #docker logs timescaledb-1
-          docker stop timescaledb-1 || true
-          
-          echo "Logging and stopping kafka-to-postgresql-v2"
-          #docker logs kafka-to-postgresql-v2-1
-          docker stop kafka-to-postgresql-v2-1 || true
-          
-          docker container prune -f || true
-          docker volume prune -f || true
-          docker system prune -f || true
+          docker logs redpanda-1 || true
+          #docker logs timescaledb-1 || true      
+          docker logs kafka-to-postgresql-v2-1 || true
+          curl -vvv http://${{ env.REDPANDA_IP }}:8082/topics
